world_frame: odom
odom_frame: odom
base_link_frame: base_link

transform_timeout: 0.2
two_d_mode: true
use_control: true
publish_tf: true

control_config: [true,false,false,
    false,false,true]

#imu0: /imu
#imu0_remove_gravitational_acceleration: true
#imu0_relative: true
#imu0_config: [false, false, false,
#    true, true, true, # yaw (mag) ???
#    false, false, false, # lin vel
#    true, true, true, # ang vel
#    true, false, false] # lin acc
#imu0_queue_size: 10
#
#imu1: /pimu
#imu1_remove_gravitational_acceleration: true
#imu1_relative: true
#imu1_config: [false,false,false,
#    true,true,true,
#    false,false,false,
#    true,true,true,
#    true,false,false]
#imu1_queue_size: 10

odom0: /vo
odom0_config: [true, true, true,
    false, false, true,
    true, true, true,
    false, false, false,
    false, false, false]
odom0_relative: true
odom0_differential: true
