#network configuration
BATCH_SIZE=16
IMG_WIDTH=320
IMG_HEIGHT=240
IMG_DEPTH=3
TIME_STEPS=4
LSTM_SIZE=1024
NUM_LSTM=2
W_COST=[1.,1.,100.]
SAVE_STEPS=100
TRAIN_STEPS=1000

# learning rate
LEARNING_RATE = 5e-3 # initial learning rate
FINAL_DECAY = 0.1
NUM_DECAY   = 5
STEPS_PER_DECAY = float(TRAIN_STEPS) / NUM_DECAY
#EPOCHS_PER_DECAY = 0.2
#STEPS_PER_EPOCH  = (2332 / BATCH_SIZE)
#STEPS_PER_DECAY  = (STEPS_PER_EPOCH * EPOCHS_PER_DECAY)
DECAY_FACTOR = 0.91
